In [22]:
import pandas as pd

In [23]:
df=pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [24]:
df.isnull().sum()
df.shape

(50000, 2)

In [25]:
df.drop_duplicates(inplace=True)
df.shape

(49582, 2)

In [26]:

#Preprocessing 
df["review"]=df["review"].str.lower()

# Preprocessing

In [27]:
import re

1. Remove URL

In [28]:
def remove_url(text):
    text=re.sub(r"https\S+","",text)
    return text
df["review"]=df["review"].apply(remove_url)

2. Remove Punctuations

In [29]:
def remove_punctuations(text):
    text=re.sub(r"[^A-Za-z0-9\s]","",text)
    return text
df["review"]=df["review"].apply(remove_punctuations)

3. Removing HTML

In [30]:
def remove_html(text):
    text=re.sub(r"<.*?>","",text)
    return text
df["review"]=df["review"].apply(remove_html)

4. Removing Stopwords

In [31]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sroy9\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\sroy9\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sroy9\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [32]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [37]:
def remove_stopwords(text):
    tokens=word_tokenize(text)
    stop_words=stopwords.words("english")
    for word in tokens:
        if word in stop_words:
            text=text.replace(word,"")
    return text
df["review"]=df["review"].apply(remove_stopwords)

In [38]:
df.head()

                                              review sentiment
0  e    revewers  nte   wtchg  1 oz epoe   hooke ...  positive
1   wderful ltle prducti br br  filming technique...  positive
2   hugh h   werful w  pen me    h ummer weeken n...  positive
3  bcy   fly   e boy jke hk   zobe   cloe   pn  f...  negative
4  peer me love   i     vu unng film  wch mr mei ...  positive

5. Stemming

In [39]:
from nltk.stem import PorterStemmer

In [40]:
def stemming(text):
    ps=PorterStemmer()
    tokens=word_tokenize(text)
    stemmed_words=[]

    for token in tokens:
        stemmed_token=ps.stem(token)
        stemmed_words.append(stemmed_token)
    return " ".join(stemmed_words)
df["review"]=df["review"].apply(stemming)